pipeline {
    agent any

    environment {
        REGISTRY = "myregistry.com"
        IMAGE = "myapp"
        APP_DIR = "configuration_management"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/affishh/docker.git']]
                ])
            }
        }

        stage('Install Dependencies') {
            steps {
                dir(APP_DIR) {
                    sh 'npm install'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir(APP_DIR) {
                    sh 'npm test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir(APP_DIR) {
                    sh 'docker build -t $REGISTRY/$IMAGE:green .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $REGISTRY/$IMAGE:green'
            }
        }

        stage('Deploy GREEN Environment') {
            steps {
                sh '''
                docker stop myapp-green || true
                docker rm myapp-green || true
                docker run -d --name myapp-green -p 5001:5000 $REGISTRY/$IMAGE:green
                '''
            }
        }

        stage('Health Check GREEN') {
            steps {
                sh '''
                echo "Checking GREEN app..."
                sleep 5
                curl -f http://localhost:5001 || exit 1
                '''
            }
        }

        stage('Switch BLUE → GREEN (Blue-Green Deployment)') {
            steps {
                sh '''
                docker stop myapp-blue || true
                docker rm myapp-blue || true
                docker tag $REGISTRY/$IMAGE:green $REGISTRY/$IMAGE:blue
                docker run -d --name myapp-blue -p 5000:5000 $REGISTRY/$IMAGE:blue
                '''
            }
        }

    }
}
