pipeline {
    agent any

    environment {
        REGISTRY = "myregistry.com"
        IMAGE = "myapp"
        BLUE_PORT = "8080"
        GREEN_PORT = "8081"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/affishh/docker.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build -t $REGISTRY/$IMAGE:latest nodeapp/
                """
            }
        }

        stage('Run Tests') {
            steps {
                sh """
                echo "Running tests..."
                ocker run --rm $REGISTRY/$IMAGE:latest npm test
                """
            }
        }

        stage('Push Image') {
            steps {
                sh """
                docker login $REGISTRY -u user -p password
                docker push $REGISTRY/$IMAGE:latest
                """
            }
        }

        stage('Deploy GREEN Environment') {
            steps {
                sh """
                echo "Deploying GREEN..."
                docker rm -f green || true
                docker run -d --name green -p ${GREEN_PORT}:80 $REGISTRY/$IMAGE:latest
                """
            }
        }

        stage('Smoke Test GREEN') {
            steps {
                sh """
                echo "Testing GREEN..."
                curl -f http://localhost:${GREEN_PORT}/health
                """
            }
        }

        stage('Switch Traffic BLUE → GREEN') {
            steps {
                sh """
                echo "Switching BLUE → GREEN..."

                docker rm -f blue || true
                docker rename green blue
                """
            }
        }
    }

    post {
        success {
            echo "Blue-Green Deployment Completed Successfully!"
        }
        failure {
            echo "Deployment Failed – Blue Environment Still Active!"
        }
    }
}
